import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import QrcodeGenerator from '../components/QrcodeGenerator'




export default function Home() {
  return (
    <>
      <Head>
        <title>QKoda</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero/>
      <main className=' font-main'>

        <QrcodeGenerator/>
      </main>
    </>
  )
}
